version: "3"

services:

  db:
    build: postgres/.
    container_name: "orders_db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_docker
    volumes:
        - /postgresql_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - net_docker

networks:
  net_docker:
    driver: bridge